version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:7
